
version: 2

models:
    - name: confirmed_cases
      description: "A model that counts confirmed cases"
      meta:
        
        measures:
          total_confirmed_cases:
            aggregation: sum
            

      columns:
          - name: total_cases_worldwide
            
