
version: 2

models:
    - name: confirmed_cases
      description: "A model that counts confirmed cases"
      meta:
        mappings:
          eventTimestamp: "date"
      columns:
          - name: total_cases_worldwide
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
