version: 2

models:
  - name: try10
    description: 'Covid19 Public Bigquery data'
    meta:   
      measures:
        total_new_confrirmed:
          sql: new_confirmed 
          aggregation: sum
        total_new_deceased:
          sql: new_deceased 
          aggregation: sum
    columns:
      - name: country_name
