version: 2

models:
  - name: test
    description: 'Covid19 Public Bigquery data'
    meta:   
      measures:
        total_confirmed_cases:
          column: new_confirmed
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_0_to_9_years:
          column: new_confirmed_age_0
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_10_to_19_years:
          column: new_confirmed_age_1
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_20_to_29_years:
          column: new_confirmed_age_2
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_30_to_39_years:
          column: new_confirmed_age_3
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_40_to_49_years:
          column: new_confirmed_age_4
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_50_to_59_years:
          column: new_confirmed_age_5
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_60_to_69_years:
          column: new_confirmed_age_6
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_70_to_79_years:
          column: new_confirmed_age_7
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_80_to_89_years:
          column: new_confirmed_age_8
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_90_to_99_years:
          column: new_confirmed_age_9
          aggregation: sum
          category: Confirmed_cases      


        total_people_deceased:
          column: new_deceased
          aggregation: sum
          category: Deceased 
        deceased_people_aged_0_to_9:
          column: new_deceased_age_0
          aggregation: sum
          category: Deceased 
        deceased_people_aged_10_to_19:
          column: new_deceased_age_1
          aggregation: sum
          category: Deceased
        deceased_people_aged_20_to_29:
          column: new_deceased_age_2
          aggregation: sum
          category: Deceased
        deceased_people_aged_30_to_39:
          column: new_deceased_age_3
          aggregation: sum
          category: Deceased
        deceased_people_aged_40_to_49:
          column: new_deceased_age_4
          aggregation: sum
          category: Deceased
        deceased_people_aged_50_to_59:
          column: new_deceased_age_5
          aggregation: sum
          category: Deceased
        deceased_people_aged_60_to_69:
          column: new_deceased_age_6
          aggregation: sum
          category: Deceased
        deceased_people_aged_70_to_79:
          column: new_deceased_age_7
          aggregation: sum
          category: Deceased
        deceased_people_aged_80_to_89:
          column: new_deceased_age_8
          aggregation: sum
          category: Deceased
        deceased_people_aged_90_to_99:
          column: new_deceased_age_9
          aggregation: sum
          category: Deceased             

        gdp_usd:
          column: gdp_usd 
          aggregation: average
          reportOptions:
            suffix: $         
        smoking_prevalence:
          column: smoking_prevalence
          category: prevalence
          aggregation: average
       
        total_new_deceased:
          column: new_deceased 
          aggregation: sum
        total_vaccinated:
          column: new_persons_vaccinated 
          aggregation: sum
        total_fully_vaccinated:
          column: new_persons_fully_vaccinated 
          aggregation: sum
        total_vaccine_doses_administered:
          column: new_vaccine_doses_administered 
          aggregation: sum
        total_recovered:
          column: new_recovered 
          aggregation: sum
        total_hospitalized_patients:
          column: new_hospitalized_patients 
          aggregation: sum
        total_intensive_care_patients:
          column: new_intensive_care_patients
          aggregation: sum 
    
    columns:
      - name: country_name
        meta:
          dimension:
            type: 'string'
      - name: date
        meta:
          dimension:
            type: 'timestamp'