version: 2

models:
  - name: test
    description: 'Covid19 Public Bigquery data'
    meta:   
      measures:
        total_confirmed_cases_worldwide:
          column: new_confirmed
          aggregation: sum
          category: Confirmed_cases

        total_confirmed_ages_0-9_years:
          column: new_confirmed_age_0
          aggregation: sum
          category: Confirmed_cases
                  
        gdp_usd:
          column: gdp_usd 
          aggregation: average
          reportOptions:
            suffix: $         
        smoking_prevalence:
          column: smoking_prevalence
          category: prevalence
          aggregation: average
       
        total_new_deceased:
          column: new_deceased 
          aggregation: sum
        total_vaccinated:
          column: new_persons_vaccinated 
          aggregation: sum
        total_fully_vaccinated:
          column: new_persons_fully_vaccinated 
          aggregation: sum
        total_vaccine_doses_administered:
          column: new_vaccine_doses_administered 
          aggregation: sum
        total_recovered:
          column: new_recovered 
          aggregation: sum
        total_hospitalized_patients:
          column: new_hospitalized_patients 
          aggregation: sum
        total_intensive_care_patients:
          column: new_intensive_care_patients
          aggregation: sum 
    
    columns:
      - name: country_name
        meta:
          dimension:
            type: 'string'
      - name: date
        meta:
          dimension:
            type: 'timestamp'