version: 2

models:
  - name: test
    description: 'Covid19 Public Bigquery data'
    meta:
      dimensions:
        restrictions_on_gatherings:
          type: string
          sql: CASE 
            WHEN {{TABLE}}.restrictions_on_gatherings = 0 THEN 'No restrictions' 
            WHEN {{TABLE}}.restrictions_on_gatherings = 1 THEN 'Low restrictions'
            WHEN {{TABLE}}.restrictions_on_gatherings = 2 THEN 'Moderate restrictions'
            WHEN {{TABLE}}.restrictions_on_gatherings = 3 THEN 'Increased restrictions'
            WHEN {{TABLE}}.restrictions_on_gatherings = 4 THEN 'Maximum restrictions'

            END
          category: counntry_imposed_restrictions
          label: 'Gatherings Restriction Level'
      measures:
        covid_mortality_rate:
          description: 'The percentage of people who died by covid in a country'
          sql: 100*sum(new_deceased)/avg(population)
          reportOptions:
            suffix: '%'

        deaths_to_confirmed_ratio:
          description: 'Vaccination doses administered normalized by the country population'
          sql: sum(new_deceased)/sum(coalesce(new_confirmed,0))

       
        vaccination_index_per_country:
          description: 'Vaccination doses administered normalized by the country population'
          sql: 100*sum(new_persons_fully_vaccinated)/avg(population)
          reportOptions:
            suffix: '%'

        ratio_of_testing_by_country_population:
          description: 'For comparison of testing between countries'
          sql: sum(new_tested)/avg(population)
        
          

        total_tested_patients:
          column: new_tested
          aggregation: sum
          category: tested_patients
       


        total_confirmed_cases:
          column: new_confirmed
          aggregation: sum
          category: Confirmed_cases
        


        total_people_deceased:
          column: new_deceased
          aggregation: sum
          category: Deceased_patients 
        
        total_vaccinated:
          column: new_persons_vaccinated 
          aggregation: sum
          category: vaccinated
        total_fully_vaccinated:
          column: new_persons_fully_vaccinated 
          aggregation: sum
          category: vaccinated
        total_vaccine_doses_admininstered:
          column: new_vaccine_doses_administered
          aggregation: sum
          category: vaccinated

        total_hospitalized_patients:
          column: new_hospitalized_patients
          aggregation: sum
          category: hospitalized_patients
        

        total_intensive_care_patients:
          column: new_intensive_care_patients
          aggregation: sum
          category: intensive_care_patients
        

        total_recovered_patients:
          column: new_recovered
          aggregation: sum
          category: recovered_patients
       

        
        total_population_male:
          column: population_male
          aggregation: average
          category: gender_specific_properties
        adult_male_mortality_rate:
          column: adult_male_mortality_rate
          aggregation: average
          category: gender_specific_properties
        adult_female_mortality_rate:
          column: adult_female_mortality_rate
          aggregation: average
          category: gender_specific_properties
        total_population_female:
          column: population_female
          aggregation: average
          category: gender_specific_properties
        total_male_patients_tested:
          column: new_tested_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_tested:
          column: new_tested_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_deceased:
          column: new_deceased_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_deceased:
          column: new_deceased_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_confirmed:
          column: new_confirmed_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_confirmed:
          column: new_confirmed_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_hospitalized:
          column: new_hospitalized_patients_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_hospitalized:
          column: new_hospitalized_patients_female
          aggregation: sum
          category: gender_specific_properties
        total_intensive_care_male_patients:
          column: new_intensive_care_patients_male
          aggregation: sum
          category: gender_specific_properties
        total_intensive_care_female_patients:
          column: new_intensive_care_patients_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_recovered:
          column: new_recovered_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_recovered:
          column: new_recovered_female
          aggregation: sum
          category: gender_specific_properties


        gdp_usd:
          column: gdp_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            suffix: $
        gdp_per_capita:
          sql: avg(gdp_usd)/avg(population) 
          category: country_specific_indices
          reportOptions:
            suffix: $          
        smoking_prevalence_index:
          column: smoking_prevalence
          category: country_specific_indices
          aggregation: average
        diabetes_prevalence_index:
          column: diabetes_prevalence
          category: country_specific_indices
          aggregation: average
        infant_mortality_rate:
          column: infant_mortality_rate
          category: country_specific_indices
          aggregation: average
        nurses_per_1000_people:
          column: nurses_per_1000
          category: country_specific_indices
          aggregation: average
        physicians_per_1000_people:
          column: physicians_per_1000
          category: country_specific_indices
          aggregation: average
        hospital_beds_per_1000_people:
          column: hospital_beds_per_1000
          category: country_specific_indices
          aggregation: average
        health_expenditure:
          column: health_expenditure_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            prefix: $
        out_of_pocket_health_expenditure:
          column: out_of_pocket_health_expenditure_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            prefix: $
        human_development_index:
          column: human_development_index
          aggregation: average
          category: country_specific_indices
        stringency_index:
          column: stringency_index
          aggregation: average
          category: country_specific_indices
        human_capital_index:
          column: human_capital_index
          aggregation: average
          category: country_specific_indices
        life_expectancy:
          column: life_expectancy
          aggregation: average
          category: country_specific_indices
        pollution_mortality_rate:
          column: pollution_mortality_rate
          aggregation: average
          category: country_specific_indices


        total_population:
          column: population
          aggregation: average
          category: country_population_properties
        population_in_the_largest_city:
          column: population_largest_city
          aggregation: average
          category: country_population_properties
        total_population_rural_areas:
          column: population_rural
          aggregation: average
          category: country_population_properties
        total_population_urban_areas:
          column: population_urban
          aggregation: average
          category: country_population_properties
        population_density:
          column: population_density
          aggregation: average
          category: country_population_properties
        population_aged_0_to_9_years:
          column: population_age_00_09
          aggregation: average
          category: country_population_properties
        population_aged_10_to_19_years:
          column: population_age_10_19
          aggregation: average
          category: country_population_properties
        population_aged_20_to_29_years:
          column: population_age_20_29
          aggregation: average
          category: country_population_properties
        population_aged_30_to_39_years:
          column: population_age_30_39
          aggregation: average
          category: country_population_properties
        population_aged_40_to_49_years:
          column: population_age_40_49
          aggregation: average
          category: country_population_properties
        population_aged_50_to_59_years:
          column: population_age_50_59
          aggregation: average
          category: country_population_properties
        population_aged_60_to_69_years:
          column: population_age_60_69
          aggregation: average
          category: country_population_properties
        population_aged_70_to_79_years:
          column: population_age_70_79
          aggregation: average
          category: country_population_properties
        population_aged_80_and_older:
          column: population_age_80_and_older
          aggregation: average
          category: country_population_properties


        average_temperature:
          column: average_temperature_celsius
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: °C
        minimum_temperature:
          column: minimum_temperature_celsius
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: °C
        maximum_temperature:
          column: maximum_temperature_celsius
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: °C
        rainfall:
          column: rainfall_mm
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: mm
        snowfall:
          column: snowfall_mm
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: mm
        dew_point:
          column: dew_point
          aggregation: average
          category: country_climate_properties
          reportOptions:
            suffix: °C
        relative_humidity:
          column: relative_humidity
          aggregation: average
          category: country_climate_properties
            
         
    
    columns:
      - name: country_name
        meta:
          dimension:
            type: 'string'
      - name: date
        meta:
          dimension:
            type: 'timestamp'
      - name: school_closing
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'School Closing Level'
      - name: workplace_closing
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'Workplace Closing Level'
      - name: cancel_public_events
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'Event Cancellation Level'
      - name: stay_at_home_requirements
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'Stay at Home Requirements Level'
      - name: restrictions_on_international_movement
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'International Movement Restriction Level'
      - name: international_travel_controls
        meta:
          dimension:
            type: 'integer'
            category: counntry_imposed_restrictions
            label: 'International Travel Control Level'
      - name: income_support
        meta:
          dimension:
            type: 'integer'
            category: country_support_measures
            label: 'Income Support Level'
      - name: debt_relief
        meta:
          dimension:
            type: 'integer'
            category: country_support_measures
            label: 'Debt Relief Level'
      - name: fiscal_measures
        meta:
          dimension:
            type: 'integer'
            category: country_support_measures
            label: 'Fiscal Measures Level'
      - name: international_support
        meta:
          dimension:
            type: 'integer'
            category: country_support_measures
            label: 'International Support Level'
      - name: testing_policy
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Testing Policy Level'
      - name: contact_tracing
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Contact Tracing Level'
      - name: emergency_investment_in_healrthcare
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Emergency Investment in Healthcare Level'
      - name: investment_in_vaccines
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Investment in Vaccines Level'
      - name: facial_coverings
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Facial Coverings Level'
      - name: vaccination_policy
        meta:
          dimension:
            type: 'integer'
            category: country_imposed_policies
            label: 'Vaccination Policy Level'
      - name: aggregation_level
        meta:
          dimension:
            type: 'integer'
            label: 'aggregation level'

            





