version: 2

models:
  - name: confirmed_cases_covid1
    description: 'Covid19 Public Bigquery data'
    meta:
    
      measures: 
        new_confirmed:
          aggregation: sum
        new_deceased:
          aggregation: sum
    columns:
      - name: country_name
      - name: date