version: 2

models:
  - name: covid19_data1
    description: 'Covid19 Public Bigquery data'
    meta:
    
      measures: 
        new_confirmed:
          aggregation: count
        new_deceased:
          aggregation: count
    columns:
      - name: country_name
      - name: date