version: 2

models:
  - name: total_confirmed_cases_by_day
    description: 'Covid19 Public Bigquery data'
    meta:
      eventTimestamp: "date"  
    columns:
      - name: cumulative_confirmed
      