version: 2

models:
  - name: test
    description: 'Covid19 Public Bigquery data'
    meta:   
      measures:
        total_tested_patients:
          column: new_tested
          aggregation: sum
          category: tested_patients
        tested_patients_aged_0_to_9_years:
          column: new_tested_age_0
          aggregation: sum
          category: tested_patients
        tested_patients_aged_10_to_19_years:
          column: new_tested_age_1
          aggregation: sum
          category: tested_patients
        tested_patients_aged_20_to_29_years:
          column: new_tested_age_2
          aggregation: sum
          category: tested_patients
        tested_patients_aged_30_to_39_years:
          column: new_tested_age_3
          aggregation: sum
          category: tested_patients
        tested_patients_aged_40_to_49_years:
          column: new_tested_age_4
          aggregation: sum
          category: tested_patients
        tested_patients_aged_50_to_59_years:
          column: new_tested_age_5
          aggregation: sum
          category: tested_patients
        tested_patients_aged_60_to_69_years:
          column: new_tested_age_6
          aggregation: sum
          category: tested_patients
        tested_patients_aged_70_to_79_years:
          column: new_tested_age_7
          aggregation: sum
          category: tested_patients
        tested_patients_aged_80_to_89_years:
          column: new_tested_age_8
          aggregation: sum
          category: tested_patients
        tested_patients_aged_90_to_99_years:
          column: new_tested_age_9
          aggregation: sum
          category: tested_patients


        total_confirmed_cases:
          column: new_confirmed
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_0_to_9_years:
          column: new_confirmed_age_0
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_10_to_19_years:
          column: new_confirmed_age_1
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_20_to_29_years:
          column: new_confirmed_age_2
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_30_to_39_years:
          column: new_confirmed_age_3
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_40_to_49_years:
          column: new_confirmed_age_4
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_50_to_59_years:
          column: new_confirmed_age_5
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_60_to_69_years:
          column: new_confirmed_age_6
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_70_to_79_years:
          column: new_confirmed_age_7
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_80_to_89_years:
          column: new_confirmed_age_8
          aggregation: sum
          category: Confirmed_cases
        confirmed_cases_aged_90_to_99_years:
          column: new_confirmed_age_9
          aggregation: sum
          category: Confirmed_cases      


        total_people_deceased:
          column: new_deceased
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_0_to_9:
          column: new_deceased_age_0
          aggregation: sum
          category: Deceased_patients  
        deceased_people_aged_10_to_19:
          column: new_deceased_age_1
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_20_to_29:
          column: new_deceased_age_2
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_30_to_39:
          column: new_deceased_age_3
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_40_to_49:
          column: new_deceased_age_4
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_50_to_59:
          column: new_deceased_age_5
          aggregation: sum
          category: Deceased
        deceased_people_aged_60_to_69:
          column: new_deceased_age_6
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_70_to_79:
          column: new_deceased_age_7
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_80_to_89:
          column: new_deceased_age_8
          aggregation: sum
          category: Deceased_patients 
        deceased_people_aged_90_to_99:
          column: new_deceased_age_9
          aggregation: sum
          category: Deceased_patients 

        total_vaccinated:
          column: new_persons_vaccinated 
          aggregation: sum
          category: vaccinated
        total_fully_vaccinated:
          column: new_person_fully_vaccinated 
          aggregation: sum
          category: vaccinated
        total_vaccine_doses_admininstered:
          column: new_vaccine_doses_administered
          aggregation: sum
          category: vaccinated

        total_hospitalized_patients:
          column: new_hospitalized_patients
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_0_to_9:
          column: new_hospitalized_patients_age_0
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_10_to_19:
          column: new_hospitalized_patients_age_1
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_20_to_29:
          column: new_hospitalized_patients_age_2
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_30_to_39:
          column: new_hospitalized_patients_age_3
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_40_to_49:
          column: new_hospitalized_patients_age_4
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_50_to_59:
          column: new_hospitalized_patients_age_5
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_60_to_69:
          column: new_hospitalized_patients_age_6
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged70_to_79:
          column: new_hospitalized_patients_age_7
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_80_to_89:
          column: new_hospitalized_patients_age_8
          aggregation: sum
          category: hospitalized_patients
        hospitalized_patients_aged_90_to_99:
          column: new_hospitalized_patients_age_9
          aggregation: sum
          category: hospitalized_patients

        total_intensive_care_patients:
          column: new_intensive_care_patients
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_0_to_9:
          column: new_intensive_care_patients_age_0
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_10_to_19:
          column: new_intensive_care_patients_age_1
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_20_to_29:
          column: new_intensive_care_patients_age_2
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_30_to_39:
          column: new_intensive_care_patients_age_3
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_40_to_49:
          column: new_intensive_care_patients_age_4
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_50_to_59:
          column: new_intensive_care_patients_age_5
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_60_to_69:
          column: new_intensive_care_patients_age_6
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_70_to_79:
          column: new_intensive_care_patients_age_7
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_80_to_89:
          column: new_intensive_care_patients_age_8
          aggregation: sum
          category: intensive_care_patients
        intensive_care_patients_aged_90_to_99:
          column: new_intensive_care_patients_age_9
          aggregation: sum
          category: intensive_care_patients   

        total_recovered_patients:
          column: new_recovered
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_0_to_9:
          column: new_recovered_age_0
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_10_to_19:
          column: new_recovered_age_1
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_20_to_29:
          column: new_recovered_age_2
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_30_to_39:
          column: new_recovered_age_3
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_40_to_49:
          column: new_recovered_age_4
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_50_to_59:
          column: new_recovered_age_5
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_60_to_69:
          column: new_recovered_age_6
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_70_to_79:
          column: new_recovered_age_7
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_80_to_89:
          column: new_recovered_age_8
          aggregation: sum
          category: recovered_patients
        recovered_patients_aged_90_to_99:
          column: new_recovered_age_9
          aggregation: sum
          category: recovered_patients

        
        total_population_male:
          column: population_male
          aggregation: average
          category: gender_specific_properties
        total_population_female:
          column: population_female
          aggregation: average
          category: gender_specific_properties
        total_male_patients_tested:
          column: new_tested_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_tested:
          column: new_tested_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_deceased:
          column: new_deceased_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_deceased:
          column: new_deceased_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_confirmed:
          column: new_confirmed_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_confirmed:
          column: new_confirmed_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_hospitalized:
          column: new_hospitalized_patients_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_hospitalized:
          column: new_hospitalized_patients_female
          aggregation: sum
          category: gender_specific_properties
        total_intensive_care_male_patients:
          column: new_intensive_care_patients_male
          aggregation: sum
          category: gender_specific_properties
        total_intensive_care_female_patients:
          column: new_intensive_care_patients_female
          aggregation: sum
          category: gender_specific_properties
        total_male_patients_recovered:
          column: new_recovered_male
          aggregation: sum
          category: gender_specific_properties
        total_female_patients_recovered:
          column: new_recovered_female
          aggregation: sum
          category: gender_specific_properties


        gdp_usd:
          column: gdp_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            suffix: $
        gdp_per_capita:
          column: gdp_per_capita_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            suffix: $          
        smoking_prevalence_index:
          column: smoking_prevalence
          category: country_specific_indices
          aggregation: average
        diabetes_prevalence_index:
          column: diabetes_prevalence
          category: country_specific_indices
          aggregation: average
        infant_mortality_rate:
          column: infant_mortality_rate
          category: country_specific_indices
          aggregation: average
        nurses_per_1000_people:
          column: nurse_per_1000
          category: country_specific_indices
          aggregation: average
        physicians_per_1000_people:
          column: physicians_per_1000
          category: country_specific_indices
          aggregation: average
        health_expenditure:
          column: health_expenditure_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            suffix: $
        out_of_pocket_health_expenditure:
          column: out_of_pocket_health_expenditure_usd 
          aggregation: average
          category: country_specific_indices
          reportOptions:
            suffix: $
        human_development_index:
          column: human_development_index
          aggregation: average
          category: country_specific_indices


        total_population:
          column: population
          aggregation: average
          category: country_population_properties
        total_population_rural_areas:
          column: population_rural
          aggregation: average
          category: country_population_properties
        total_population_urban_areas:
          column: population_urban
          aggregation: average
          category: country_population_properties
        population_density:
          column: population_density
          aggregation: average
          category: country_population_properties
        population_aged_0_to_9_years:
          column: population_age_00_09
          aggregation: average
          category: country_population_properties
        population_aged_10_to_19_years:
          column: population_age_10_19
          aggregation: average
          category: country_population_properties
        population_aged_20_to_29_years:
          column: population_age_20_29
          aggregation: average
          category: country_population_properties
        population_aged_30_to_39_years:
          column: population_age_30_39
          aggregation: average
          category: country_population_properties
        population_aged_40_to_49_years:
          column: population_age_40_49
          aggregation: average
          category: country_population_properties
        population_aged_50_to_59_years:
          column: population_age_50_59
          aggregation: average
          category: country_population_properties
        population_aged_60_to_69_years:
          column: population_age_60_69
          aggregation: average
          category: country_population_properties
        population_aged_70_to_79_years:
          column: population_age_70_79
          aggregation: average
          category: country_population_properties
        population_aged_80_to_89_years:
          column: population_age_80_89
          aggregation: average
          category: country_population_properties
        population_aged_90_to_99_years:
          column: population_age_90_99
          aggregation: average
          category: country_population_properties

        
       
        
        
        
        
         
    
    columns:
      - name: country_name
        meta:
          dimension:
            type: 'string'
      - name: date
        meta:
          dimension:
            type: 'timestamp'