version: 2

models:
  - name: try7
    description: 'Covid19 Public Bigquery data'
    meta:   
      measures:
        new_confrirmed: 
          aggregation: sum 
    columns:
      - name: country_name
