version: 2

models:
  - name: try3
    description: 'Covid19 Public Bigquery data'  
    measures:
      new_confrirmed :
        columnn: new_confirmed 
        sql: new_confirmed
        aggregation: sum 
    columns:
      - name: country_name
